using System;
using System.Diagnostics;
using System.IO;
using System.Windows;
using Microsoft.Win32;
using SaveProfileSwitcher.App.Models;
using SaveProfileSwitcher.App.Services;
namespace SaveProfileSwitcher.App.Views;
public partial class SettingsDialog : Window
{
    private Settings settings = new();
    public SettingsDialog() { InitializeComponent(); LoadSettings(); }
    private void LoadSettings() { settings = SettingsService.Instance.LoadSettings(); GlobalSaveModeComboBox.SelectedIndex = settings.GlobalDefaultSaveMode switch { SaveMode.SymlinkOrJunction => 0, SaveMode.MoveAndSwap => 1, _ => 2 }; SafetyStagingCheckBox.IsChecked = settings.SafetyStagingEnabled; ConfirmSwitchingCheckBox.IsChecked = settings.ConfirmBeforeSwitching; PreventRunningCheckBox.IsChecked = settings.PreventSwitchWhileGameRunning; AutomaticBackupsCheckBox.IsChecked = settings.EnableAutomaticBackups; RetentionSlider.Value = Math.Clamp(settings.MaxBackupsPerGame, 1, 20); BackupBeforeSwitchingCheckBox.IsChecked = settings.BackupBeforeSwitching; BackupBeforeRestoringCheckBox.IsChecked = settings.BackupBeforeRestoring; BackupBeforeOverwriteCheckBox.IsChecked = settings.BackupBeforeOverwrite; BackupPathTextBox.Text = settings.DefaultBackupLocation; ApplicationRootTextBox.Text = settings.ApplicationRoot; ProfilesRootTextBox.Text = settings.ProfilesRoot; BackupsRootTextBox.Text = settings.BackupsRoot; LogsRootTextBox.Text = settings.LogsRoot; AutomaticDetectionCheckBox.IsChecked = settings.EnableAutomaticExeDetection; PortableSearchCheckBox.IsChecked = settings.SearchPortableEmulatorFolders; AppDataSearchCheckBox.IsChecked = settings.SearchAppDataAndDocuments; CustomEmulatorPathTextBox.Text = settings.CustomEmulatorExecutable; LoggingCheckBox.IsChecked = settings.EnableLogging; DarkThemeCheckBox.IsChecked = settings.DarkMode; TextSizeSlider.Value = Math.Clamp(settings.TextSize, 10, 24); CompactLayoutCheckBox.IsChecked = settings.CompactLayout; ShowGameIdsCheckBox.IsChecked = settings.ShowGameIds; ShowSavePathsCheckBox.IsChecked = settings.ShowSavePaths; }
    private void SaveSettings_Click(object sender, RoutedEventArgs e) { settings.GlobalDefaultSaveMode = GlobalSaveModeComboBox.SelectedIndex switch { 0 => SaveMode.SymlinkOrJunction, 1 => SaveMode.MoveAndSwap, _ => SaveMode.CopyAndOverwrite }; settings.SafetyStagingEnabled = SafetyStagingCheckBox.IsChecked == true; settings.ConfirmBeforeSwitching = ConfirmSwitchingCheckBox.IsChecked == true; settings.PreventSwitchWhileGameRunning = PreventRunningCheckBox.IsChecked == true; settings.EnableAutomaticBackups = AutomaticBackupsCheckBox.IsChecked == true; settings.MaxBackupsPerGame = (int)Math.Clamp(RetentionSlider.Value, 1, 20); settings.BackupBeforeSwitching = BackupBeforeSwitchingCheckBox.IsChecked == true; settings.BackupBeforeRestoring = BackupBeforeRestoringCheckBox.IsChecked == true; settings.BackupBeforeOverwrite = BackupBeforeOverwriteCheckBox.IsChecked == true; settings.DefaultBackupLocation = BackupPathTextBox.Text.Trim(); settings.ApplicationRoot = ApplicationRootTextBox.Text.Trim(); settings.ProfilesRoot = ProfilesRootTextBox.Text.Trim(); settings.BackupsRoot = BackupsRootTextBox.Text.Trim(); settings.LogsRoot = LogsRootTextBox.Text.Trim(); settings.EnableAutomaticExeDetection = AutomaticDetectionCheckBox.IsChecked == true; settings.SearchPortableEmulatorFolders = PortableSearchCheckBox.IsChecked == true; settings.SearchAppDataAndDocuments = AppDataSearchCheckBox.IsChecked == true; settings.CustomEmulatorExecutable = CustomEmulatorPathTextBox.Text.Trim(); settings.EnableLogging = LoggingCheckBox.IsChecked == true; settings.DarkMode = DarkThemeCheckBox.IsChecked == true; settings.TextSize = (int)Math.Clamp(TextSizeSlider.Value, 10, 24); settings.CompactLayout = CompactLayoutCheckBox.IsChecked == true; settings.ShowGameIds = ShowGameIdsCheckBox.IsChecked == true; settings.ShowSavePaths = ShowSavePathsCheckBox.IsChecked == true; SettingsService.Instance.SaveSettings(settings); DialogResult = true; }
    private void BrowseBackupPath_Click(object sender, RoutedEventArgs e) { var d = new OpenFolderDialog(); if (d.ShowDialog(this) == true) BackupPathTextBox.Text = d.FolderName; }
    private void BrowseCustomEmulator_Click(object sender, RoutedEventArgs e) { var d = new OpenFileDialog { Filter = "Executable files|*.exe|All files|*.*" }; if (d.ShowDialog(this) == true) CustomEmulatorPathTextBox.Text = d.FileName; }
    private static void OpenPath(string path) { if (Directory.Exists(path)) Process.Start(new ProcessStartInfo(path) { UseShellExecute = true }); }
    private void OpenBackupFolder_Click(object sender, RoutedEventArgs e) => OpenPath(BackupPathTextBox.Text);
    private void OpenApplicationRoot_Click(object sender, RoutedEventArgs e) => OpenPath(ApplicationRootTextBox.Text);
    private void OpenProfilesRoot_Click(object sender, RoutedEventArgs e) => OpenPath(ProfilesRootTextBox.Text);
    private void OpenBackupsRoot_Click(object sender, RoutedEventArgs e) => OpenPath(BackupsRootTextBox.Text);
    private void OpenLogsRoot_Click(object sender, RoutedEventArgs e) => OpenPath(LogsRootTextBox.Text);
    private void OpenDataFile_Click(object sender, RoutedEventArgs e) { string path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "SaveProfileSwitcher", "data.json"); if (File.Exists(path)) Process.Start(new ProcessStartInfo("notepad.exe", "\"" + path + "\"") { UseShellExecute = true }); }
    private void ExportDiagnostics_Click(object sender, RoutedEventArgs e) { MessageBox.Show(this, "Diagnostic export is not available until a diagnostic export service is configured.", "Diagnostics", MessageBoxButton.OK, MessageBoxImage.Information); }
    private void ClearOldLogs_Click(object sender, RoutedEventArgs e) { if (MessageBox.Show(this, "Clear old logs?", "Confirm", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes && Directory.Exists(LogsRootTextBox.Text)) foreach (string file in Directory.GetFiles(LogsRootTextBox.Text)) File.Delete(file); }
    private void Cancel_Click(object sender, RoutedEventArgs e) => DialogResult = false;
}
